version: 2

sources:
  - name: dev
    database: db
    tables:
      - name: row_weather_data
        columns:
          - name: id
          - name: city
          - name: temperature
          - name: weather_desc
          - name: wind_speed
          - name: time
          - name: inserted_at
          - name: utc_offset  
